spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/team11
    username: team11
    password: 1234
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: localhost
      port: 6379
      username: default
      password: systempass
eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

management:
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0

server:
  host: localhost
  gateway:
    port: 19091
  swagger:
    host: localhost