CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

INSERT INTO p_hubs (hub_id, name, address, latitude, longitude, is_deleted, created_at,
                    updated_at)
VALUES (uuid_generate_v4(), '서울특별시 센터', '서울특별시 송파구 송파대로 55', 37.4742, 127.1236,
        false, now(), now()),
       (uuid_generate_v4(), '경기 북부 센터', '경기도 고양시 덕양구 권율대로 570', 37.6500, 126.8737,
        false, now(), now()),
       (uuid_generate_v4(), '경기 남부 센터', '경기도 이천시 덕평로 257-21', 37.1896, 127.3750,
        false, now(), now()),
       (uuid_generate_v4(), '부산광역시 센터', '부산 동구 중앙대로 206', 35.1176, 129.0450,
        false, now(), now()),
       (uuid_generate_v4(), '대구광역시 센터', '대구 북구 태평로 161', 35.8758, 128.5961,
        false, now(), now()),
       (uuid_generate_v4(), '인천광역시 센터', '인천 남동구 정각로 29', 37.4560, 126.7052,
        false, now(), now()),
       (uuid_generate_v4(), '광주광역시 센터', '광주 서구 내방로 111', 35.1600, 126.8514,
        false, now(), now()),
       (uuid_generate_v4(), '대전광역시 센터', '대전 서구 둔산로 100', 36.3503, 127.3846,
        false, now(), now()),
       (uuid_generate_v4(), '울산광역시 센터', '울산 남구 중앙로 201', 35.5379, 129.3112,
        false, now(), now()),
       (uuid_generate_v4(), '세종특별자치시 센터', '세종특별자치시 한누리대로 2130', 36.4800, 127.2890,
        false, now(), now()),
       (uuid_generate_v4(), '강원특별자치도 센터', '강원특별자치도 춘천시 중앙로 1', 37.8800, 127.7279,
        false, now(), now()),
       (uuid_generate_v4(), '충청북도 센터', '충북 청주시 상당구 상당로 82', 36.6353, 127.4914,
        false, now(), now()),
       (uuid_generate_v4(), '충청남도 센터', '충남 홍성군 홍북읍 충남대로 21', 36.6590, 126.6729,
        false, now(), now()),
       (uuid_generate_v4(), '전북특별자치도 센터', '전북특별자치도 전주시 완산구 효자로 225', 35.8194, 127.1063,
        false, now(), now()),
       (uuid_generate_v4(), '전라남도 센터', '전남 무안군 삼향읍 오룡길 1', 34.8174, 126.4654,
        false, now(), now()),
       (uuid_generate_v4(), '경상북도 센터', '경북 안동시 풍천면 도청대로 455', 36.5761, 128.5057,
        false, now(), now()),
       (uuid_generate_v4(), '경상남도 센터', '경남 창원시 의창구 중앙대로 300', 35.2378, 128.6919,
        false, now(), now());

INSERT INTO p_hub_paths (hub_paths_id, start_hub_id, end_hub_id, duration, path, is_deleted, created_at,
                         updated_at)
VALUES (uuid_generate_v4(), (SELECT hub_id FROM p_hubs WHERE name = '서울특별시 센터'),
        (SELECT hub_id FROM p_hubs WHERE name = '경기 북부 센터'), '02:00:00', '서울-경기 북부', false, now(), now()),
       (uuid_generate_v4(), (SELECT hub_id FROM p_hubs WHERE name = '경기 북부 센터'),
        (SELECT hub_id FROM p_hubs WHERE name = '경기 남부 센터'), '01:30:00', '경기 북부-경기 남부', false, now(),
        now()),
       (uuid_generate_v4(), (SELECT hub_id FROM p_hubs WHERE name = '경기 남부 센터'),
        (SELECT hub_id FROM p_hubs WHERE name = '부산광역시 센터'), '04:00:00', '경기 남부-부산', false, now(), now()),
       (uuid_generate_v4(), (SELECT hub_id FROM p_hubs WHERE name = '부산광역시 센터'),
        (SELECT hub_id FROM p_hubs WHERE name = '대구광역시 센터'), '02:00:00', '부산-대구', false, now(), now()),
       (uuid_generate_v4(), (SELECT hub_id FROM p_hubs WHERE name = '대구광역시 센터'),
        (SELECT hub_id FROM p_hubs WHERE name = '인천광역시 센터'), '03:00:00', '대구-인천', false, now(), now()),
       (uuid_generate_v4(), (SELECT hub_id FROM p_hubs WHERE name = '인천광역시 센터'),
        (SELECT hub_id FROM p_hubs WHERE name = '광주광역시 센터'), '03:30:00', '인천-광주', false, now(), now()),
       (uuid_generate_v4(), (SELECT hub_id FROM p_hubs WHERE name = '광주광역시 센터'),
        (SELECT hub_id FROM p_hubs WHERE name = '대전광역시 센터'), '02:00:00', '광주-대전', false, now(), now()),
       (uuid_generate_v4(), (SELECT hub_id FROM p_hubs WHERE name = '대전광역시 센터'),
        (SELECT hub_id FROM p_hubs WHERE name = '울산광역시 센터'), '03:00:00', '대전-울산', false, now(), now()),
       (uuid_generate_v4(), (SELECT hub_id FROM p_hubs WHERE name = '울산광역시 센터'),
        (SELECT hub_id FROM p_hubs WHERE name = '세종특별자치시 센터'), '03:30:00', '울산-세종', false, now(),
        now()),
       (uuid_generate_v4(), (SELECT hub_id FROM p_hubs WHERE name = '세종특별자치시 센터'),
        (SELECT hub_id FROM p_hubs WHERE name = '강원특별자치도 센터'), '04:00:00', '세종-강원', false, now(), now()),
       (uuid_generate_v4(), (SELECT hub_id FROM p_hubs WHERE name = '강원특별자치도 센터'),
        (SELECT hub_id FROM p_hubs WHERE name = '충청북도 센터'), '01:30:00', '강원-충북', false, now(), now()),
       (uuid_generate_v4(), (SELECT hub_id FROM p_hubs WHERE name = '충청북도 센터'),
        (SELECT hub_id FROM p_hubs WHERE name = '충청남도 센터'), '01:00:00', '충북-충남', false, now(), now()),
       (uuid_generate_v4(), (SELECT hub_id FROM p_hubs WHERE name = '충청남도 센터'),
        (SELECT hub_id FROM p_hubs WHERE name = '전북특별자치도 센터'), '02:00:00', '충남-전북', false, now(), now()),
       (uuid_generate_v4(), (SELECT hub_id FROM p_hubs WHERE name = '전북특별자치도 센터'),
        (SELECT hub_id FROM p_hubs WHERE name = '전라남도 센터'), '03:00:00', '전북-전남', false, now(), now()),
       (uuid_generate_v4(), (SELECT hub_id FROM p_hubs WHERE name = '전라남도 센터'),
        (SELECT hub_id FROM p_hubs WHERE name = '경상북도 센터'), '04:00:00', '전남-경북', false, now(), now()),
       (uuid_generate_v4(), (SELECT hub_id FROM p_hubs WHERE name = '경상북도 센터'),
        (SELECT hub_id FROM p_hubs WHERE name = '경상남도 센터'), '02:30:00', '경북-경남', false, now(), now());