spring:
  config:
    activate:
      on-profile: dev
  data:
    redis:
      host: localhost
      port: 6379
      username: default
      password: systempass
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - 'http://localhost:19091'
              - 'https://localhost:19091'

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/
  swagger:
    host: localhost