spring:
  config:
    activate:
      on-profile: dev
  data:
    redis:
      host: localhost
      port: 6379
      username: default
      password: systempass
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - 'http://localhost:19092'
              - 'http://localhost:19093'
              - 'http://localhost:19094'
              - 'http://localhost:19095'
              - 'http://localhost:19096'
              - 'http://localhost:19097'
              - 'http://localhost:19098'
eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/
  swagger:
    host: localhost