server:
  port: 19091
spring:
  profiles:
    default: dev
  main:
    web-application-type: reactive
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        cors-configurations:
          '[/**]':
            allow-credentials: true
            allowedHeaders:
              - x-requested-with
              - Authorization
              - content-type
              - credential
              - X-AUTH-TOKEN
              - X-CSRF-TOKEN
              - X-User-Name
            exposedHeaders:
              - x-requested-with
              - Authorization
              - content-type
              - credential
              - X-AUTH-TOKEN
              - X-CSRF-TOKEN
              - X-User-Name
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
      routes:
        - id: service
          uri: lb://service
          predicates:
            - Path=/api/**
      discovery:
        locator:
          enabled: true
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /api/service/v3/api-docs
        name: Service API
  api-docs:
    enabled: true

service:
  jwt:
    secret-key: #JWT 키