spring:
  profiles:
    default: dev
  application:
    name: order-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        highlight_sql: true
server:
  port: 19092
  servlet:
    context-path: /api

springdoc:
  swagger-ui:
    path: /service/swagger-ui
  api-docs:
    path: /service/v3/api-docs